#!/usr/bin/env bash

set -e -u
set -o pipefail

# write some cool doc here

function main () {
	while getopts "h" opt; do
		case ${opt} in
			h)	# help message
				cat << EOF
Usage: $(basename $0) [OPTION]...
Options: -h: show this help dialog
EOF
				exit 0
				;;
			?)
				echo "Unknown option, exiting now" >&2
				exit 1
				;;
		esac
	done
    shift $((OPTIND - 1))
    [[ "${1:-}" == '--' ]] && shift
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
