" ensures compatibility with ViM-related packages in Debian
runtime! debian.vim

syntax on
colorscheme koehler

set nocompatible
set showcmd                             " Show partial command in status line and selected characters/lines in visual mode
set showmatch                           " Show matching brackets.
set ignorecase                          " Ignore case when matching
set smartcase                           " Do smart case matching
set incsearch                           " Incremental search
set autowrite                           " Automatically save before commands like :next and :make
set mouse=a                             " Enable mouse usage (all modes)
set number                              " display line numbers on left
set relativenumber                      " display relative numbers
set hlsearch                            " highlighting of search term
set autoindent
set scrolloff=5                         " show 5 lines above or below cursor position
set backspace=indent,eol,start          " allow backspace across lines and automatic indentation
set expandtab                           " expand tabs to spaces
set shiftwidth=4                        " number of spaces to use for autoindenting
set smarttab                            " insert tabs on the start of a line according to shiftwidth, not tabstop
set shiftround                          " use multiple of shiftwidth when indenting with '<' and '>'
set tabstop=4                           " tabs have a width of 4 chars
set splitright                          " new window opens on right instead of left
set splitbelow                          " new window opens on bottom instead of top
set wildmenu                            " show menu when using tab completion
set wildmode=list:longest,full          " list matches and complete longest common part, then cycle through matches
set wildignore=*.pyc,*.o,*.obj,*.swp
set pastetoggle=<F2>                    " disable paste-unfriendly features when pasting in insert mode
set ttimeoutlen=60                      " Fast escape out of insert mode
set path+=**                            " search down into subfolders, provides tab completion for all related tasks
set encoding=utf-8                      " welcome to the 21st century
set lazyredraw                          " faster macros
set nomodeline                          " disable modelines (security)
set shortmess+=aI                       " avoid 'hit enter', no welcome message
set ttyfast                             " fast internet connection
set autoread                            " automatically reread modified files, this turns out to be BS but I'm leaving it anyways
set title                               " change the terminal's title

set list
set listchars=tab:>.,trail:.,extends:#,nbsp:. " show trailing tabs and spaces

if has('cmdline_info')
    " a ruler
    set ruler
    " a ruler on steroids
    set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%)
endif
if has('statusline')
    " always show a status line
    set laststatus=2
    " a statusline, also on steroids
    set statusline=%<%f\ %=\:\b%n\[%{strlen(&ft)?&ft:'none'}/%{&encoding}/%{&fileformat}]%m%r%w\ %l,%c%V\ %P
endif
" Remove toolbar from gvim
if has('gui_running')
    set guioptions=-t
    set cursorline
    map <silent><A-t> :tabnew<CR>
    map <silent><A-Right> :tabnext<CR>
    map <silent><A-Left> :tabprevious<CR>
endif
if $TMUX == ''
  set clipboard+=unnamed
endif

" highlight cursorline and cursorcolumn
highlight CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
highlight CursorColumn cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
" \c will toggle highlighting on and off (to make it easy to locate the cursor in a large file)
nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>

" no sudo? no problem! save with 'w!!'
cmap w!! w !sudo tee % >/dev/null


" highlight the 81st column when we go past it
call matchadd('ColorColumn', '\%81v', 100)

" File browsing:
let g:netrw_banner=0
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_liststyle=3
"let g:netrw_list_hide=netrw_gitignore#Hide()
"let g:netrw_list_hide.=',\(^\|\s\s)\zs\.\S\+'

" compatibility with vim-latexsuite
set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"

let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts=1

if has("autocmd")
" Vim loads indentation rules and plugins according to the detected filetype.
    filetype plugin indent on
" Vim jumps to the last position when reopening a file
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
" In some files, like HTML and XML files, tabs are fine and showing them is really annoying,
    autocmd filetype html,xml set listchars-=tab:>.
endif

function! ShowSpaces(...)
    let @/='\v(\s+$)|( +\ze\t)'
    let oldhlsearch=&hlsearch
    if !a:0
        let &hlsearch=!&hlsearch
    else
        let &hlsearch=a:1
    end
    return oldhlsearch
endfunction

function! TrimSpaces() range
    let oldhlsearch=ShowSpaces(0)
    execute a:firstline.",".a:lastline."substitute ///gec"
    let &hlsearch=oldhlsearch
endfunction

command! -bar -nargs=0 -range=% TrimSpaces <line1>,<line2>call TrimSpaces()
" Create the 'tags' file
command! MakeTags !maketags
command! -nargs=0 Reload source ~/.vim/vimrc

" Use more natural key movement on wrapped lines.
nnoremap j gj
nnoremap k gk
nnoremap gj 5j
nnoremap gk 5k
" Keep selection when indent/dedenting in select mode.
vnoremap > >gv
vnoremap < <gv
" Make Y copy to end of line instead of be an alias for yy
nnoremap Y y$
" Who uses ';' anyways?
nnoremap ; :

" Ctrl+\ : open ctag definition in new tab
map <C-\> :tab split<CR>:exec("tag ".expand("<cword>"))<CR>
" Alt+] : open ctag definition in vertical split
map <A-]> :vsp <CR>:exec("tag ".expand("<cword>"))<CR>

" Swap 2 panes with 4 keystrokes
" 'sw' to select 1st pane
" move to new pane
" 'mw' to exchange selected pane with current pane
function! SelectWindowSwap()
    let g:markedWinNum = winnr()
endfunction

function! MoveWindowSwap()
    "Mark destination
    let curNum = winnr()
    let curBuf = bufnr( "%" )
    exe g:markedWinNum . "wincmd w"
    "Switch to source and shuffle dest->source
    let markedBuf = bufnr( "%" )
    "Hide and open so that we aren't prompted and keep history
    exe 'hide buf' curBuf
    "Switch to dest and shuffle source->dest
    exe curNum . "wincmd w"
    "Hide and open so that we aren't prompted and keep history
    exe 'hide buf' markedBuf
endfunction

function! Bgrep(pattern)
    exe vimgrep a:pattern %
    exe cwin
endfunction

noremap <leader>sw :call SelectWindowSwap()<CR>
noremap <leader>mw :call MoveWindowSwap()<CR>

noremap <leader>bash :r ~/.vim/snippets/bash-snippet<CR>kdd
noremap <leader>py :r ~/.vim/snippets/python-snippet<CR>kdd
noremap <leader>clang :r ~/.vim/snippets/c-snippet<CR>kdd
noremap <leader>java :r ~/.vim/snippets/java-snippet<CR>kdd

nmap <F4> :TagbarToggle<CR>
nnoremap <leader>udt :UndotreeToggle<CR>

nnoremap <leader>no :set nonumber<CR>:set norelativenumber<CR>
nnoremap <leader>nb :set number<CR>:set norelativenumber<CR>
nnoremap <leader>nr :set number<CR>:set relativenumber<CR>

" to please the Olde Gods
iabbrev cthuf Ia! Ia! Cthulhu fhtagn! Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn! Cthulhu fhtagn! Cthulhu fhtagn!

" dragvisuals plugin key bindings
vmap  <expr>  <LEFT>   DVB_Drag('left')
vmap  <expr>  <RIGHT>  DVB_Drag('right')
vmap  <expr>  <DOWN>   DVB_Drag('down')
vmap  <expr>  <UP>     DVB_Drag('up')
vmap  <expr>  D        DVB_Duplicate()

" vim-vmath keybindings
vmap <expr>  ++  VMATH_YankAndAnalyse()
nmap         ++  vip++

call plug#begin('~/.vim/plugged')
    " Plug 'mxw/vim-jsx'
    " Plug 'vim-syntastic/syntastic'
    Plug 'keith/swift.vim'
    Plug 'majutsushi/tagbar'
    Plug 'mariappan/dragvisuals.vim'
    Plug 'mbbill/undotree'
    Plug 'nixon/vim-vmath'
    Plug 'pangloss/vim-javascript'
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-surround'
    Plug 'udalov/kotlin-vim'
    Plug 'vim-airline/vim-airline'
    Plug 'vim-erlang/vim-erlang-compiler'
    Plug 'vim-erlang/vim-erlang-omnicomplete'
    Plug 'vim-erlang/vim-erlang-runtime'
    Plug 'vim-erlang/vim-erlang-tags'
call plug#end()
