" ensures compatibility with ViM-related packages in Debian
runtime! debian.vim

runtime modules/settings.vim
runtime modules/keymap.vim
runtime modules/functions.vim
runtime modules/plugin_config.vim
runtime modules/autocmds.vim

call plug#begin('~/.vim/plugged')
if hostname() != 'DD-WRT' && $USER != "root"
    Plug 'albfan/ag.vim'
    Plug 'fatih/vim-go'
    "Plug 'ludovicchabant/vim-gutentags'
    Plug 'itchyny/lightline.vim'
    Plug 'junegunn/fzf'
    Plug 'keith/swift.vim'
    Plug 'mariappan/dragvisuals.vim'
    Plug 'maxmellon/vim-jsx-pretty'
    Plug 'mbbill/undotree'
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
    Plug 'nixon/vim-vmath'
    Plug 'pangloss/vim-javascript'
    Plug 'rhysd/git-messenger.vim'
    Plug 'tpope/vim-commentary'
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-surround'
    Plug 'udalov/kotlin-vim'
    Plug 'vim-erlang/vim-erlang-compiler'
    Plug 'vim-erlang/vim-erlang-omnicomplete'
    Plug 'vim-erlang/vim-erlang-runtime'
    Plug 'vim-erlang/vim-erlang-tags'
    Plug 'vim-syntastic/syntastic'
endif
call plug#end()
