#!/usr/bin/env bash

# seriously, fuck those aliases
unalias ln cp mv 2>/dev/null

alias diff="diff -wbBdu"
alias info="info --vi-keys"
alias reload='source ~/.bashrc'
alias hreload="history -r"
alias savepane='tmux capture-pane -S -; tmux save-buffer'
alias tmux_alert='tmux select-pane -P "bg=colour1"'
alias treset='tmux select-pane -P "bg=colour0"'
alias uhtop='htop -u $USER'
alias watch="watch --differences"
alias sat='sudo $(which sat)'
alias psql="env PGCONNECT_TIMEOUT=2 psql"

# enable color support of ls and also add handy aliases
if command -v dircolors >/dev/null; then
    eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias colorgrep='grep --color=always'
fi

# rename from util-linux sucks, use perl rename utility for PCRE
if [ -x /usr/bin/prename ]; then
    alias rename=prename
fi

# personal
alias binclock='watch -n1 "echo \"obase=2;\$(date +%s)\" | bc"'
alias syncstatus='dropbox filestatus $(find ~/Dropbox -type f)|grep "syncing"|uniq'

# I did a funny
alias 42='echo The answer to Life, the Universe and Everything.'
alias starwars='telnet towel.blinkenlights.nl'

if command -v cowsay >/dev/null; then
    # shellcheck disable=SC2154
    alias allcows='cowsay -l | sed "1d"|tr " " "\n"|while read f; do cowsay -f $f $f;done'
    alias randcow='cowsay -f $(cowsay -l|sed "1d"|tr " " "\n"|grep -vE "sodomized|telebears|head-in"|shuf -n1)'
fi
alias canihazip="curl https://icanhazip.com"
