#!/usr/bin/env bash

# seriously, fuck those aliases
unalias ln cp mv 2> /dev/null

alias diff="diff -wbBdu"
alias info="info --vi-keys"
alias reload='source ~/.bashrc'
alias hreload="history -r"
alias savepane='tmux capture-pane -S -; tmux save-buffer'
alias tmux_alert='tmux select-pane -P "bg=colour1"'
alias treset='tmux select-pane -P "bg=colour0"'
alias uhtop='htop -u $USER'
alias watch="watch --differences"
alias psql="env PGCONNECT_TIMEOUT=5 psql"
alias less="less -R"
alias kpcli=keepassxc-cli
alias DID_I_FUCKING_STUTTER='sudo $(history -p !!)'
alias tor2dlp="yt-dlp --proxy 'socks5://localhost:9150'"
# shellcheck disable=SC2142
alias trimlines='awk "{if (length(\$0) <= $COLUMNS) {print}}"'

# enable color support of ls and also add handy aliases
if command -v dircolors > /dev/null; then
    eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias colorgrep='grep --color=always'
fi

# rename from util-linux sucks, use perl rename utility for PCRE
# shellcheck disable=SC2144
if [ -x /usr/bin/prename ]; then
    alias rename=prename
elif [ -x /usr/bin/perl-rename ]; then
    alias rename=perl-rename
elif [ -x /opt/local/bin/rename-5.* ]; then
    # shellcheck disable=SC2139
    alias rename=/opt/local/bin/rename-5.*
fi

if command -v cowsay > /dev/null; then
    # shellcheck disable=SC2154
    alias allcows='cowsay -l | sed "1d"|tr " " "\n"|while read f; do cowsay -f $f $f;done'
    alias randcow='cowsay -f $(cowsay -l|sed "1d"|tr " " "\n"|grep -vE "sodomized|telebears|head-in"|shuf -n1)'
fi
alias canihazip="curl -s https://icanhazip.com"
