#!/usr/bin/env bash

alias dadjoke="curl https://icanhazdadjoke.com --silent; echo"

# Shorthand clone from github
function hclone()
{
    local url
    if [[ $1 == "-p" ]]; then
        url="git@github.com:${2}.git"
        shift
    else
        url="git://github.com/${1}.git"
    fi
    git clone "$url"
}

function weather()
{
    # shellcheck disable=SC2001
    location="$(sed 's/ /%20/g' <<< "${@}")"
    curl "v2.wttr.in/${location}?m"
}

function setup-ssh-key-login()
{
    local desthost="${1}"
    shift
    local keyfile="${1:-${HOME}/.ssh/keys/${desthost}.id_ed25519}"
    shift

    if [ -n "${desthost}" ] && [ -n "${keyfile}" ]; then
        ssh-keygen -t ed25519 -f "${keyfile}"
        ssh-copy-id -i "${keyfile}" "${desthost}"
    else
        # shellcheck disable=SC2016
        printf 'Undefined:\n$desthost=%s\n$keyfile=%s\n' "${desthost}" "${keyfile}"
    fi
}

function archive_dl_music()
{
    mv -iv ~/Downloads/*.mp3 ~/Music/Songs/
}

function isblocked()
{
    grep "${1}" /etc/hosts
}

function twlookup()
{
    phone_number="$1"
    shift
    curl -sX GET "https://lookups.twilio.com/v1/PhoneNumbers/${phone_number}?CountryCode=US&Type=carrier&Type=caller-name&Fields=line_type_intelligence" \
        -u "${TWILIO_TOKEN}" | jq
}

function twlookup_whitepages()
{
    phone_number="$1"
    shift
    curl -sX GET "https://lookups.twilio.com/v1/PhoneNumbers/${phone_number}?AddOns=whitepages_pro_caller_id" \
        -u "${TWILIO_TOKEN}" | jq
}

function pgkill()
{
    pattern="$1"
    shift
    pgrep -alfi "${pattern}" | fzf | awk '{print $1}' | xargs -r kill
}

function wikisole()
{
    dig +short txt "$*.wp.dg.cx"
}

function worddef()
{
    curl -s "https://api.dictionaryapi.dev/api/v2/entries/en/$*" | jq
}

function trackinfo()
{
    artist="$(osascript -e 'tell application "spotify" to artist of current track')"
    album="$(osascript -e 'tell application "spotify" to album of current track')"
    title="$(osascript -e 'tell application "spotify" to name of current track')"
    printf "%s -> %s:%s\n" "${artist}" "${album}" "${title}"
}

function firefox_addons()
{
    profile_name=${1:-default}
    case "${OSTYPE}" in
        darwin*)
            FIREFOX_HOMEDIR="$HOME/Library/Application Support/Firefox"
            ;;
        linux-gnu)
            FIREFOX_HOMEDIR=~/.mozilla/firefox
            ;;
        *)
            echo Not Found
            ;;
    esac
    # shellcheck disable=2015
    profile_dir="${FIREFOX_HOMEDIR}/$(test -d "${FIREFOX_HOMEDIR-x}" \
        && awk '/^\[Profile[0-9]\]$/,/^$/ {printf ("%s@", $0)} END {printf "\n"}' "${FIREFOX_HOMEDIR}/profiles.ini" \
        | grep "Name=${profile_name}" \
        | sed -E 's/.*Path=([^@]*)@.*/\1/')"
    workspace_dir="$(mktemp -d)"

    out=""

    for extpath in "${profile_dir}"/extensions/*; do
        ext_filename="$(basename "${extpath}")"
        if [ "${ext_filename}" != staged ]; then
            cp "$profile_dir/extensions/${ext_filename}" "${workspace_dir}"
            unzip -d "${workspace_dir}" "${workspace_dir}/$ext_filename" manifest.json > /dev/null
            ext_name="$(jq '{"name": .name, "app_id": .applications.gecko.id, "homepage_url": .homepage_url}' "${workspace_dir}/manifest.json")"
            out="${out}{\"${ext_filename}\": ${ext_name}},"
            rm -r "${workspace_dir:?}"/*
        fi
    done
    out="${out%%,}"
    echo "[${out}]"
}
