#!/usr/bin/env -S bash

# Shorthand clone from github
function hclone()
{
    local url
    if [[ $1 == "-p" ]]; then
        url="git@github.com:${2}.git"
        shift
    else
        url="git://github.com/${1}.git"
    fi
    git clone "$url"
}

function weather()
{
    location="$(sed 's/ /%20/g' <<< ${*})"
    curl "v2.wttr.in/${location}?m"
}

function setup-ssh-key-login()
{
    local desthost="${1}"
    shift
    local keyfile="${1:-${HOME}/.ssh/keys/${desthost}.id_ed25519}"
    shift

    if [ -n "${desthost}" ] && [ -n "${keyfile}" ]; then
        ssh-keygen -t ed25519 -f "${keyfile}"
        ssh-copy-id -i "${keyfile}" "${desthost}"
    else
        # shellcheck disable=SC2016
        printf 'Undefined:\n$desthost=%s\n$keyfile=%s\n' "${desthost}" "${keyfile}"
    fi
}

function archive_dl_music()
{
    mv -iv ~/Downloads/*.mp3 ~/Music/Songs/
}

function isblocked()
{
    grep "${1}" /etc/hosts
}

function twlookup()
{
    phone_number="$1"
    shift
    curl -sX GET "https://lookups.twilio.com/v1/PhoneNumbers/${phone_number}?CountryCode=US&Type=carrier&Type=caller-name&Fields=line_type_intelligence" \
        -u "${TWILIO_TOKEN}" | jq
}

function twlookup_whitepages()
{
    phone_number="$1"
    shift
    curl -sX GET "https://lookups.twilio.com/v1/PhoneNumbers/${phone_number}?AddOns=whitepages_pro_caller_id" \
        -u "${TWILIO_TOKEN}" | jq
}

function pgkill()
{
    pattern="$1"
    shift
    pgrep -alfi "${pattern}" | fzf | awk '{print $1}' | xargs -r kill
}

function wikisole()
{
    host -t txt "$*.wp.dg.cx"
}

function trackinfo()
{
    artist="$(osascript -e 'tell application "spotify" to artist of current track')"
    album="$(osascript -e 'tell application "spotify" to album of current track')"
    title="$(osascript -e 'tell application "spotify" to name of current track')"
    printf "%s -> %s:%s\n" "${artist}" "${album}" "${title}"
}
