#!/usr/bin/env -S bash

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
export EDITOR=vim
#export GOPATH=~/Documents/code/thirdparty/golang-libs
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export DO_NOT_TRACK=1

# shellcheck disable=SC1090,SC1091
test -f "${HOME}/.local/share/bash/perscreds" && source "${HOME}/.local/share/bash/perscreds"

if command -v direnv > /dev/null; then
    eval "$(direnv hook bash)"
fi
