#!/bin/bash

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
export EDITOR=vim
#export LANG="C"
#export LC_ALL="C"
GCLOUD_SDK_BASEDIR='/opt/local/google-cloud-sdk'
