#!/bin/bash

COLUMNS=$(tput cols)
LINES=$(tput lines)

which fortune >/dev/null 2>&1
if [ $? == 0 ]; then
    which cowsay >/dev/null 2>&1
    if [ $? == 0 ] && [[ $COLUMNS -ge 80 ]] && [[ $LINES -ge 28 ]]; then
      fortune -a|randcow
    else
      fortune -a
    fi
fi
