#!/bin/bash

COLUMNS=$(tput cols)
LINES=$(tput lines)

which fortune 2>/dev/null
if [ $? == 0 ]; then
    which cowsay 2>/dev/null
    if [ $? == 0 ] && [[ $COLUMNS -ge 80 ]] && [[ $LINES -ge 28 ]]; then
      fortune -s|randcow
    else
      fortune -s
    fi
fi
