#!/usr/bin/env -S bash

DATA_DIR="$HOME/data"
DB_DIR="${DATA_DIR}/postgres/kilidb"
TOMCAT_DIR=/opt/tomcat
JOBOX_CREDS_FILE="${XDG_DATA_DIR:-$HOME/.local/share}/bash/joboxcreds"
JOBOX_SHELL="${jobox}/MissionPeak/joboxshell/bash"
test -r "${JOBOX_SHELL}" && source "${JOBOX_SHELL}"
source /opt/local/share/nvm/nvm.sh
