#!/usr/bin/env bash

# shellcheck disable=SC2034
JOBOX_DATA_DIR="$HOME/data/work/jobox"

# shellcheck disable=SC2034
JOBOX_DB_DIR="${JOBOX_DATA_DIR}/postgres"

# shellcheck disable=SC2034
JOBOX_TOMCAT_DIR=/opt/tomcat/9

# shellcheck disable=SC2034
JOBOX_CREDS_FILE="${XDG_DATA_DIR:-$HOME/.local/share}/bash/joboxcreds"

# shellcheck disable=SC2154
JOBOX_SHELL="${jobox}/MissionPeak/joboxshell/bash"

# shellcheck disable=SC1090
test -r "${JOBOX_SHELL}" && source "${JOBOX_SHELL}"
