#!/usr/bin/env bash

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)"'

# launch facebook in a separate firefox profile
alias fb='firefox -no-remote -P Facebook >/dev/null 2>&1 &'
alias cp='cp --backup=numbered'
alias ln='ln --backup=numbered'
alias mv='mv -f --backup=numbered'
alias open='xdg-open'
alias utop='top -u $USER'

# the extensions for 'which' apparently aren't standard... redhat-based has,
# debian-based doesn't
# shellcheck disable=SC2230
if which --version > /dev/null 2>&1; then
    alias which='(alias; declare -f) | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde --read-functions'
fi

function clipboard()
{
    if [ "${#}" -eq 0 ]; then
        xclip -in
    else
        file="${1}"
        shift
        test -r "${file}" && xclip -in < "${file}"
    fi
    xclip -out
}
