#!/bin/bash

export PATH=$(sed "s,$HOME/bin,$HOME/bin:/opt/local/bin:/opt/local/sbin," <<< $PATH)
alias ls="ls -G"
alias grep='grep --color=always'
alias utop="top -U $USER"
alias shuf=gshuf

if [ ! -x /opt/local/bin/rename ] && [ -x /opt/local/bin/rename-5.26 ]; then
	alias rename=rename-5.26
fi
