#!/bin/bash

if [ "$(type -t ls)" != "alias" ]; then
    alias ls="ls -G"
    alias grep='grep --color=always'
fi
alias utop="top -U $USER"
export COCOAPODS_DISABLE_STATS='true'
#alias simulator="/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator -CurrentDeviceUDID AE350978-A3A3-44E5-A77F-45028962E4E7"
function free ()
{
    vm_stat | perl -ne '/page size of (\d+)/ and $size=$1; /Pages\s+([^:]+)[^\d]+(\d+)/ and printf("%-16s % 16.2f Mi\n", "$1:", $2 * $size / 1048576);'
}
