#!/usr/bin/env -S bash

export GOPATH=$src/go

function init_cscope()
{
    if [ $# != 1 ]; then
        lang=c
    else
        lang=$1
        shift
    fi

    case $lang in
        c)
            find . -name '*.cpp' -o -name '*.c++' -o -name '*.c' -o \
                -name '*.cu' \
                -name '*.hpp' -o -name '*.h' \
                | grep -v 'CMakeFiles' > cscope.in
            cscope -qRb -i cscope.in
            rm cscope.in
            ;;
        py)
            echo "Python language"
            echo "IMPLEMENT ME"
            ;;
        *)
            echo "Unsupported language; write your own thing, k?"
            ;;
    esac
}

function venv()
{
    save_pwd="$(pwd)"
    while [ "$(pwd)" != "/" ] && [ ! -f ./.venv/bin/activate ]; do
        up
    done
    retval=0
    # shellcheck disable=SC1091
    test -f ./.venv/bin/activate && source ./.venv/bin/activate || retval=1
    cd "${save_pwd}" || return "${retval}"
    return "${retval}"
}

# print list of buck targets under a dir in fbcode
function targets()
{
    dir="${1:-.}"
    shift
    basedir="$(realpath "${dir}" 2> /dev/null)"

    while [ "${basedir}" != "/" ] && [ ! -f "${basedir}/WORKSPACE" ]; do
        basedir="$(realpath "${basedir}/..")"
    done
    if [ ! -f "${basedir}/WORKSPACE" ]; then
        return
    fi

    target_files=("$(find "${dir}" -name BUILD)")
    for t in "${target_files[@]}"; do
        dir="$(realpath "$(dirname "${t}")" | perl -pe "s#${basedir}#/#")"
        perl -lne 'm!\s*name\s*=\s*['\''"](\w+)['\''"],$! and print q('"$dir:"').$1' "${t}"
    done | sort
}
