#!/usr/bin/env bash

export GOPATH=$src/go

function init_cscope()
{
    if [ $# != 1 ]; then
        lang=c
    else
        lang=$1
        shift
    fi

    case $lang in
        c)
            find . -name '*.cpp' -o -name '*.c++' -o -name '*.c' -o \
                -name '*.cu' \
                -name '*.hpp' -o -name '*.h' \
                | grep -v 'CMakeFiles' > cscope.in
            cscope -qRb -i cscope.in
            rm cscope.in
            ;;
        py)
            echo "Python language"
            echo "IMPLEMENT ME"
            ;;
        *)
            echo "Unsupported language; write your own thing, k?"
            ;;
    esac
}

function venv()
{
    save_pwd="$(pwd)"
    while [ "$(pwd)" != "/" ] && [ ! -f ./.venv/bin/activate ]; do
        up
    done
    retval=0
    # shellcheck disable=SC1091
    test -f ./.venv/bin/activate && source ./.venv/bin/activate || retval=1
    cd "${save_pwd}" || return "${retval}"
    return "${retval}"
}

function httpcode()
{
    code="$1"; shift
    perl -MHTTP::Status=status_message -E 'my $c=shift; say "$c -> ", status_message($c)' "${code}"
    echo "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/${code}"
}

# print list of buck targets under a dir in fbcode
function targets()
{
    dir="${1:-.}"
    shift
    basedir="$(realpath "${dir}" 2> /dev/null)"

    while [ "${basedir}" != "/" ] && [ ! -f "${basedir}/WORKSPACE" ]; do
        basedir="$(realpath "${basedir}/..")"
    done
    if [ ! -f "${basedir}/WORKSPACE" ]; then
        return
    fi

    target_files=("$(find "${dir}" -name BUILD)")
    for t in "${target_files[@]}"; do
        dir="$(realpath "$(dirname "${t}")" | perl -pe "s#${basedir}#/#")"
        perl -lne 'm!\s*name\s*=\s*['\''"](\w+)['\''"],$! and print q('"$dir:"').$1' "${t}"
    done | sort
}

if command -v rlwrap > /dev/null; then
    alias yaegi="rlwrap yaegi"
fi

function browsecommit()
{
    commit="$1"
    shift
    open "$(git config --get remote.origin.url | sed -E 's/\.git$//;s/gh:/https:\/\/github.com\//;s/^[a-zA-Z0-9_]+@/https:\/\//;s/:/\//2')/commit/${commit}"
}

function readprompt()
{
    clipboard "$(find ~/data/prompts -type f|grep -v '\.git'|fzf --query "${1}")"
}
