#!/usr/bin/env bash

THERME_DATA_DIR="$HOME/data/therme"

# shellcheck disable=SC2034
THERME_DB_DIR="${THERME_DATA_DIR}/postgres"

# shellcheck disable=SC2034
THERME_CREDS_FILE="${XDG_DATA_DIR:-$HOME/.local/share}/bash/thermecreds"

# shellcheck disable=SC2154
THERME_SHELL="${therme}/dakar/thermeshell/bash"

# shellcheck disable=SC1090
test -r "${THERME_SHELL}" && source "${THERME_SHELL}"
