#!/usr/bin/env bash

ln -s ~/.local/share/discord ~/.config/discord
ln -s ~/.local/share/YouTube\ Music ~/.config/YouTube\ Music
ln -s ~/.local/share/rua ~/.config/rua
ln -s ~/.local/share/Electron ~/.config/Electron
rm -r ~/.config/pulse; ln -s ~/.local/share/pulse ~/.config/pulse
if [ "$(which dwm)" == "" ]; then
    cp "$(git rev-parse --show-toplevel)/.xsession" ~/
fi
