#!/usr/bin/env bash

set -e -u
set -o pipefail

# write some cool doc here

function git_setup_qubes_pgp ()
{
    git config --global include.path ~/.config/git/qubes-gpg
}

function usage ()
{
    cat << EOF
Usage: $(basename $0) [OPTION]...
Options: --help, -h: show this help dialog
EOF
}

function main ()
{
    while getopts "h-:" opt; do
        case ${opt} in
            h)  # help message
                usage
                exit 0
                ;;
            -)
                case "${OPTARG}" in
                    help)
                        usage
                        exit 0
                        ;;
                    *)
                        printf 'Unknown option, exiting now\n' >&2
                        exit 1
                        ;;
                esac
                ;;
            ?)
                printf 'Unknown option, exiting now\n' >&2
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))
    [[ "${1:-}" == '--' ]] && shift

    git_setup_qubes_pgp
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
